config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get '/chats/:title', to: 'chats#show', as: :chat
  # post '/chats', to: 'chats#create', as: :chats

  devise_for :users, controllers: { registrations: 'registrations' }
  resource :chats, only: :create
  get '/chats/:title', to: 'chats#show', as: :chat
  resource :messages, only: :create
  root 'chats#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
# frozen_string_literal: true

class Chat < ApplicationRecord
  has_many :messages, -> { sorted }, dependent: :destroy
  belongs_to :user
  before_create { self.title = SecureRandom.hex(3) }
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user

  scope :sorted, -> { order(:id) }
  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :chats, dependent: :destroy
  has_many :messages, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
# frozen_string_literal: true

class ChatsController < ApplicationController
  def index
    @new_chat = Chat.new
    @chats = Chat.all
  end

  def create
    @new_chat = Chat.new(user: current_user)

    @new_chat.broadcast_append_to :chats if @new_chat&.save
  end

  def show
    @chat = Chat.find_by!(title: params[:title])
    @messages = @chat.messages
    @new_message = current_user&.messages&.build
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  def create
    @new_message = current_user.messages.build(strong_params)

    @new_message.broadcast_append_to @new_message.chat if @new_message.save
  end

  private

  def strong_params
    params.require(:message).permit(:chat_id, :body)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  private

  def after_sign_up_path_for(_resource)
    root_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/chats/_chat.html.erb
<%= link_to chat.title, chat_path(chat.title), class: "text-current text-blue-500 mr-4", target: "_blank", rel: "noopener noreferrer" %>

app/views/chats/index.html.erb
<%= turbo_stream_from :chats %>

<%= turbo_frame_tag :chats do %>
  <%= render @chats %>
<% end %>

<% if current_user.present? %>
  <%= form_with model: @new_chat do |f| %>
    <%= f.submit "Create chat", class: "group relative flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 w-32" %>
  <% end %>
<% end %>

app/views/chats/show.html.erb
<%= turbo_stream_from @chat %>
<%= turbo_stream_from [current_user, @chat] %>

<div class="flex flex-col h-96 justify-between">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8" id="chat-container">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8" id="chat_<%= @chat.id %>_messages">
      <%= turbo_frame_tag :messages do %>
        <%= render @messages %>
      <% end %>
    </div>
  </div>
</div>

<%= form_with model: @new_message, data: { controller: "chat_refresh", action: "turbo:submit-end->chat_refresh#clearInput" } do |f| %>
  <div class="rounded-md shadow-sm -space-y-px">
    <%= f.text_field :body, autofocus: true, required: true, placeholder: "Your text", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
    <%= f.hidden_field :chat_id, value: @chat.id %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Telegr</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>

<div class="min-h-full">
  <nav class="bg-gray-800">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 items-center justify-between">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <a href="/">
              <img class="h-8 w-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
            </a>
          </div>
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline space-x-4">
              <% if user_signed_in? %>
                <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
              <% else %>
                <%= link_to "Sign in", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>

                <%= link_to "Sign up", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="md:hidden" id="mobile-menu">
      <div class="space-y-1 px-2 pt-2 pb-3 sm:px-3">
          <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>

            <%= link_to "Sign up", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
          <% end %>
      </div>
    </div>
  </nav>

  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Telegr</h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
      <%= yield %>
    </div>
  </main>
</div>
</body>
</html>

app/views/messages/_message.html.erb
<div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg my-4 py-2 pl-1">
  <div class="flex flex-row">
    <div class="basis-1/12"><%= l(message.created_at, format: :short) %></div>
    <div class="basis-3/12"><%= message.user.email %></div>
    <div class="basis-7/12"><%= message.body %></div>
  </div>
</div>